version: "3.7"

networks:
  web-graffiti-network:
    driver: bridge

services:
  web-graffiti-gluetun:
    image: qmcgaw/gluetun
    container_name:  web-graffiti-gluetun
    networks:
      - web-graffiti-network
    cap_add:
      - NET_ADMIN
    volumes:
      - ./gluetun:/gluetun
      - ./secrets/gluetun-auth.toml:/gluetun-auth.toml
    env_file:
      - ./secrets/gluetun.env
    environment:
      - VPN_PORT_FORWARDING=on
      - PORT_FORWARD_ONLY=true
      - SERVER_REGIONS="CA Vancouver"
      - HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH=/gluetun-auth.toml
    ports:
      - 5554:5554
    restart: always

  web-graffiti-slskd:
    image: slskd/slskd:latest
    container_name: web-graffiti-slskd
    network_mode: container:web-graffiti-gluetun
    user: "1000:100"
    environment:
      - SLSKD_DOWNLOADS_DIR=/storage/downloads
      - SLSKD_SHARED_DIR=/storage
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_HTTP_PORT=5554
      - SLSKD_DISK_LOGGER=true
      - SLSKD_NO_AUTH=true
      - SLSKD_SWAGGER=true
      - SLSKD_UPLOAD_SPEED_LIMIT=1000000
      - SLSKD_DOWNLOAD_SPEED_LIMIT=1000000
      - SLSKD_UPLOAD_SLOTS=500
      - SLSKD_DOWNLOAD_SLOTS=500
    env_file:
      - ./secrets/slskd.env
    volumes:
      - /storage/web-graffiti:/storage
      - /storage/media/tv:/storage/tv
      - ./slskd:/app
    depends_on:
      - web-graffiti-gluetun
    restart: always

  web-graffiti:
    build: ./web-graffiti
    container_name: web-graffiti
    networks:
      - web-graffiti-network
    environment:
      - TARGET_SIZE=10000 #GiB
      - DOWNLOAD_CHUNK_SIZE=100 #GiB
      - REMOVE_CHUNK_SIZE=10 #GiB
      - UPDATE_PORT_TIMER=30 #Minutes
      - QUEUE_DOWNLOADS_TIMER=2 #Hours
      - PROCESS_DOWNLOADS_TIMER=30 #Minutes
      - PROCESS_UPLOADS_TIMER=12 #Hours
      - MAX_FOLDERS_PER_USER=1
      - MAX_DOWNLOAD_TIME=4 #Hours
      - SLSKD_DOWNLOADS_DIR=/storage/downloads
    env_file:
      - ./secrets/web-graffiti.env
    volumes:
      - ./slskd:/slskd
      - /storage/web-graffiti:/storage
    depends_on:
      - web-graffiti-slskd
    restart:
        always


  
