version: "3.7"
services:
  web-graffiti-gluetun:
    image: qmcgaw/gluetun
    container_name:  web-graffiti-gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - ./gluetun:/gluetun
    env_file:
      - ./secrets/gluetun.env
    environment:
      - VPN_PORT_FORWARDING=on
      - PORT_FORWARD_ONLY=true
    network_mode: bridge
    ports: 
      - 2048:2048
    restart: always
  web-graffiti-slskd:
    image: slskd/slskd
    container_name: web-graffiti-slskd
    network_mode: container:web-graffiti-gluetun
    user: 1000:100
    environment:
      - SLSKD_DOWNLOADS_DIR=/media
      - SLSKD_SHARED_DIR=/media
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_HTTP_PORT=2048
      - SLSKD_DISK_LOGGER=true
    env_file:
      - ./secrets/slskd.env
      - ./secrets/mysql.env
    volumes:
      - ./media:/media
      - ./slskd:/app
    depends_on:
      - web-graffiti-gluetun
    restart: always
  web-graffiti:
    build: ./web-graffiti
    container_name: web-graffiti
    depends_on:
      - web-graffiti-slskd
      - web-graffiti-mysql
    restart: 
        always
  web-graffiti-mysql:
    image: mysql:8.0
    container_name: web-graffiti-mysql
    restart: always
    env_file:
      - ./secrets/mysql.env 
    volumes:
      - ./db:/var/lib/mysql